openapi: 3.0.0
info:
  title: MultiTenant Company App
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /tenants/create:
    post:
      tags:
        - App Main Tenant
      summary: Create New Company & add new db
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Sandeep Neupane
                email: sandeep@gmail.com
                password: sandeep123
                companyName: Lumbini Tech
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /tenants:
    get:
      tags:
        - App Main Tenant
      summary: Get All Tenant
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /tenants/{id}:
    delete:
      tags:
        - App Main Tenant
      summary: Delete the company and tenant
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /employees/{tenantId}/create:
    post:
      tags:
        - Employee Tenant
      summary: Create New Employees to specific tenant
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Dhiren Thapa
      parameters:
        - name: tenantId
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /employees:
    get:
      tags:
        - Employee Tenant
      summary: Get all Employees
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}